// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Claw.Save
{

using global::System;
using global::FlatBuffers;

public enum Quality : sbyte
{
  White = 0,
  Green = 1,
  Blue = 2,
  Purple = 3,
  Red = 4,
  Rainbow = 5,
};

public enum Currency : sbyte
{
  Coins = 0,
  Tokens = 1,
};

public struct Wallet : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static Wallet GetRootAsWallet(ByteBuffer _bb) { return GetRootAsWallet(_bb, new Wallet()); }
  public static Wallet GetRootAsWallet(ByteBuffer _bb, Wallet obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Wallet __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Coins { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Tokens { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<Claw.Save.Wallet> CreateWallet(FlatBufferBuilder builder,
      uint coins = 0,
      uint tokens = 0) {
    builder.StartTable(2);
    Wallet.AddTokens(builder, tokens);
    Wallet.AddCoins(builder, coins);
    return Wallet.EndWallet(builder);
  }

  public static void StartWallet(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddCoins(FlatBufferBuilder builder, uint coins) { builder.AddUint(0, coins, 0); }
  public static void AddTokens(FlatBufferBuilder builder, uint tokens) { builder.AddUint(1, tokens, 0); }
  public static Offset<Claw.Save.Wallet> EndWallet(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Claw.Save.Wallet>(o);
  }
};

public struct InventoryEntry : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static InventoryEntry GetRootAsInventoryEntry(ByteBuffer _bb) { return GetRootAsInventoryEntry(_bb, new InventoryEntry()); }
  public static InventoryEntry GetRootAsInventoryEntry(ByteBuffer _bb, InventoryEntry obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public InventoryEntry __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string ItemId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetItemIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetItemIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetItemIdArray() { return __p.__vector_as_array<byte>(4); }
  public uint Quantity { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<Claw.Save.InventoryEntry> CreateInventoryEntry(FlatBufferBuilder builder,
      StringOffset item_idOffset = default(StringOffset),
      uint quantity = 0) {
    builder.StartTable(2);
    InventoryEntry.AddQuantity(builder, quantity);
    InventoryEntry.AddItemId(builder, item_idOffset);
    return InventoryEntry.EndInventoryEntry(builder);
  }

  public static void StartInventoryEntry(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddItemId(FlatBufferBuilder builder, StringOffset itemIdOffset) { builder.AddOffset(0, itemIdOffset.Value, 0); }
  public static void AddQuantity(FlatBufferBuilder builder, uint quantity) { builder.AddUint(1, quantity, 0); }
  public static Offset<Claw.Save.InventoryEntry> EndInventoryEntry(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // item_id
    return new Offset<Claw.Save.InventoryEntry>(o);
  }

  public static VectorOffset CreateSortedVectorOfInventoryEntry(FlatBufferBuilder builder, Offset<InventoryEntry>[] offsets) {
    Array.Sort(offsets, (Offset<InventoryEntry> o1, Offset<InventoryEntry> o2) => Table.CompareStrings(Table.__offset(4, o1.Value, builder.DataBuffer), Table.__offset(4, o2.Value, builder.DataBuffer), builder.DataBuffer));
    return builder.CreateVectorOfTables(offsets);
  }

  public static InventoryEntry? __lookup_by_key(int vectorLocation, string key, ByteBuffer bb) {
    byte[] byteKey = System.Text.Encoding.UTF8.GetBytes(key);
    int span = bb.GetInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = Table.__indirect(vectorLocation + 4 * (start + middle), bb);
      int comp = Table.CompareStrings(Table.__offset(4, bb.Length - tableOffset, bb), byteKey, bb);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return new InventoryEntry().__assign(tableOffset, bb);
      }
    }
    return null;
  }
};

public struct GrabRecord : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static GrabRecord GetRootAsGrabRecord(ByteBuffer _bb) { return GetRootAsGrabRecord(_bb, new GrabRecord()); }
  public static GrabRecord GetRootAsGrabRecord(ByteBuffer _bb, GrabRecord obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GrabRecord __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long UnixMs { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string MachineId { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMachineIdBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetMachineIdBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetMachineIdArray() { return __p.__vector_as_array<byte>(6); }
  public string ItemId { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetItemIdBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetItemIdBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetItemIdArray() { return __p.__vector_as_array<byte>(8); }
  public Claw.Save.Quality Quality { get { int o = __p.__offset(10); return o != 0 ? (Claw.Save.Quality)__p.bb.GetSbyte(o + __p.bb_pos) : Claw.Save.Quality.White; } }
  public bool Success { get { int o = __p.__offset(12); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<Claw.Save.GrabRecord> CreateGrabRecord(FlatBufferBuilder builder,
      long unix_ms = 0,
      StringOffset machine_idOffset = default(StringOffset),
      StringOffset item_idOffset = default(StringOffset),
      Claw.Save.Quality quality = Claw.Save.Quality.White,
      bool success = false) {
    builder.StartTable(5);
    GrabRecord.AddUnixMs(builder, unix_ms);
    GrabRecord.AddItemId(builder, item_idOffset);
    GrabRecord.AddMachineId(builder, machine_idOffset);
    GrabRecord.AddSuccess(builder, success);
    GrabRecord.AddQuality(builder, quality);
    return GrabRecord.EndGrabRecord(builder);
  }

  public static void StartGrabRecord(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddUnixMs(FlatBufferBuilder builder, long unixMs) { builder.AddLong(0, unixMs, 0); }
  public static void AddMachineId(FlatBufferBuilder builder, StringOffset machineIdOffset) { builder.AddOffset(1, machineIdOffset.Value, 0); }
  public static void AddItemId(FlatBufferBuilder builder, StringOffset itemIdOffset) { builder.AddOffset(2, itemIdOffset.Value, 0); }
  public static void AddQuality(FlatBufferBuilder builder, Claw.Save.Quality quality) { builder.AddSbyte(3, (sbyte)quality, 0); }
  public static void AddSuccess(FlatBufferBuilder builder, bool success) { builder.AddBool(4, success, false); }
  public static Offset<Claw.Save.GrabRecord> EndGrabRecord(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Claw.Save.GrabRecord>(o);
  }
};

public struct MachineRuntime : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static MachineRuntime GetRootAsMachineRuntime(ByteBuffer _bb) { return GetRootAsMachineRuntime(_bb, new MachineRuntime()); }
  public static MachineRuntime GetRootAsMachineRuntime(ByteBuffer _bb, MachineRuntime obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MachineRuntime __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string MachineId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMachineIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetMachineIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetMachineIdArray() { return __p.__vector_as_array<byte>(4); }
  public Claw.Save.InventoryEntry? Stock(int j) { int o = __p.__offset(6); return o != 0 ? (Claw.Save.InventoryEntry?)(new Claw.Save.InventoryEntry()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int StockLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Claw.Save.InventoryEntry? StockByKey(string key) { int o = __p.__offset(6); return o != 0 ? Claw.Save.InventoryEntry.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }
  public ushort RollingFailCount { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }

  public static Offset<Claw.Save.MachineRuntime> CreateMachineRuntime(FlatBufferBuilder builder,
      StringOffset machine_idOffset = default(StringOffset),
      VectorOffset stockOffset = default(VectorOffset),
      ushort rolling_fail_count = 0) {
    builder.StartTable(3);
    MachineRuntime.AddStock(builder, stockOffset);
    MachineRuntime.AddMachineId(builder, machine_idOffset);
    MachineRuntime.AddRollingFailCount(builder, rolling_fail_count);
    return MachineRuntime.EndMachineRuntime(builder);
  }

  public static void StartMachineRuntime(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddMachineId(FlatBufferBuilder builder, StringOffset machineIdOffset) { builder.AddOffset(0, machineIdOffset.Value, 0); }
  public static void AddStock(FlatBufferBuilder builder, VectorOffset stockOffset) { builder.AddOffset(1, stockOffset.Value, 0); }
  public static VectorOffset CreateStockVector(FlatBufferBuilder builder, Offset<Claw.Save.InventoryEntry>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateStockVectorBlock(FlatBufferBuilder builder, Offset<Claw.Save.InventoryEntry>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartStockVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddRollingFailCount(FlatBufferBuilder builder, ushort rollingFailCount) { builder.AddUshort(2, rollingFailCount, 0); }
  public static Offset<Claw.Save.MachineRuntime> EndMachineRuntime(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // machine_id
    return new Offset<Claw.Save.MachineRuntime>(o);
  }

  public static VectorOffset CreateSortedVectorOfMachineRuntime(FlatBufferBuilder builder, Offset<MachineRuntime>[] offsets) {
    Array.Sort(offsets, (Offset<MachineRuntime> o1, Offset<MachineRuntime> o2) => Table.CompareStrings(Table.__offset(4, o1.Value, builder.DataBuffer), Table.__offset(4, o2.Value, builder.DataBuffer), builder.DataBuffer));
    return builder.CreateVectorOfTables(offsets);
  }

  public static MachineRuntime? __lookup_by_key(int vectorLocation, string key, ByteBuffer bb) {
    byte[] byteKey = System.Text.Encoding.UTF8.GetBytes(key);
    int span = bb.GetInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = Table.__indirect(vectorLocation + 4 * (start + middle), bb);
      int comp = Table.CompareStrings(Table.__offset(4, bb.Length - tableOffset, bb), byteKey, bb);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return new MachineRuntime().__assign(tableOffset, bb);
      }
    }
    return null;
  }
};

public struct Profile : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static Profile GetRootAsProfile(ByteBuffer _bb) { return GetRootAsProfile(_bb, new Profile()); }
  public static Profile GetRootAsProfile(ByteBuffer _bb, Profile obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Profile __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string PlayerId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPlayerIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetPlayerIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetPlayerIdArray() { return __p.__vector_as_array<byte>(4); }
  public long CreatedUnixMs { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long LastSaveUnixMs { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public Claw.Save.Wallet? Wallet { get { int o = __p.__offset(10); return o != 0 ? (Claw.Save.Wallet?)(new Claw.Save.Wallet()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public Claw.Save.InventoryEntry? Inventory(int j) { int o = __p.__offset(12); return o != 0 ? (Claw.Save.InventoryEntry?)(new Claw.Save.InventoryEntry()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int InventoryLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Claw.Save.InventoryEntry? InventoryByKey(string key) { int o = __p.__offset(12); return o != 0 ? Claw.Save.InventoryEntry.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }
  public Claw.Save.GrabRecord? History(int j) { int o = __p.__offset(14); return o != 0 ? (Claw.Save.GrabRecord?)(new Claw.Save.GrabRecord()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int HistoryLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Claw.Save.MachineRuntime? Machines(int j) { int o = __p.__offset(16); return o != 0 ? (Claw.Save.MachineRuntime?)(new Claw.Save.MachineRuntime()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int MachinesLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Claw.Save.MachineRuntime? MachinesByKey(string key) { int o = __p.__offset(16); return o != 0 ? Claw.Save.MachineRuntime.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }
  public string LastUsedMachineId { get { int o = __p.__offset(18); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLastUsedMachineIdBytes() { return __p.__vector_as_span<byte>(18, 1); }
#else
  public ArraySegment<byte>? GetLastUsedMachineIdBytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public byte[] GetLastUsedMachineIdArray() { return __p.__vector_as_array<byte>(18); }

  public static Offset<Claw.Save.Profile> CreateProfile(FlatBufferBuilder builder,
      StringOffset player_idOffset = default(StringOffset),
      long created_unix_ms = 0,
      long last_save_unix_ms = 0,
      Offset<Claw.Save.Wallet> walletOffset = default(Offset<Claw.Save.Wallet>),
      VectorOffset inventoryOffset = default(VectorOffset),
      VectorOffset historyOffset = default(VectorOffset),
      VectorOffset machinesOffset = default(VectorOffset),
      StringOffset last_used_machine_idOffset = default(StringOffset)) {
    builder.StartTable(8);
    Profile.AddLastSaveUnixMs(builder, last_save_unix_ms);
    Profile.AddCreatedUnixMs(builder, created_unix_ms);
    Profile.AddLastUsedMachineId(builder, last_used_machine_idOffset);
    Profile.AddMachines(builder, machinesOffset);
    Profile.AddHistory(builder, historyOffset);
    Profile.AddInventory(builder, inventoryOffset);
    Profile.AddWallet(builder, walletOffset);
    Profile.AddPlayerId(builder, player_idOffset);
    return Profile.EndProfile(builder);
  }

  public static void StartProfile(FlatBufferBuilder builder) { builder.StartTable(8); }
  public static void AddPlayerId(FlatBufferBuilder builder, StringOffset playerIdOffset) { builder.AddOffset(0, playerIdOffset.Value, 0); }
  public static void AddCreatedUnixMs(FlatBufferBuilder builder, long createdUnixMs) { builder.AddLong(1, createdUnixMs, 0); }
  public static void AddLastSaveUnixMs(FlatBufferBuilder builder, long lastSaveUnixMs) { builder.AddLong(2, lastSaveUnixMs, 0); }
  public static void AddWallet(FlatBufferBuilder builder, Offset<Claw.Save.Wallet> walletOffset) { builder.AddOffset(3, walletOffset.Value, 0); }
  public static void AddInventory(FlatBufferBuilder builder, VectorOffset inventoryOffset) { builder.AddOffset(4, inventoryOffset.Value, 0); }
  public static VectorOffset CreateInventoryVector(FlatBufferBuilder builder, Offset<Claw.Save.InventoryEntry>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateInventoryVectorBlock(FlatBufferBuilder builder, Offset<Claw.Save.InventoryEntry>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartInventoryVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddHistory(FlatBufferBuilder builder, VectorOffset historyOffset) { builder.AddOffset(5, historyOffset.Value, 0); }
  public static VectorOffset CreateHistoryVector(FlatBufferBuilder builder, Offset<Claw.Save.GrabRecord>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateHistoryVectorBlock(FlatBufferBuilder builder, Offset<Claw.Save.GrabRecord>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartHistoryVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddMachines(FlatBufferBuilder builder, VectorOffset machinesOffset) { builder.AddOffset(6, machinesOffset.Value, 0); }
  public static VectorOffset CreateMachinesVector(FlatBufferBuilder builder, Offset<Claw.Save.MachineRuntime>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMachinesVectorBlock(FlatBufferBuilder builder, Offset<Claw.Save.MachineRuntime>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartMachinesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddLastUsedMachineId(FlatBufferBuilder builder, StringOffset lastUsedMachineIdOffset) { builder.AddOffset(7, lastUsedMachineIdOffset.Value, 0); }
  public static Offset<Claw.Save.Profile> EndProfile(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // player_id
    return new Offset<Claw.Save.Profile>(o);
  }

  public static VectorOffset CreateSortedVectorOfProfile(FlatBufferBuilder builder, Offset<Profile>[] offsets) {
    Array.Sort(offsets, (Offset<Profile> o1, Offset<Profile> o2) => Table.CompareStrings(Table.__offset(4, o1.Value, builder.DataBuffer), Table.__offset(4, o2.Value, builder.DataBuffer), builder.DataBuffer));
    return builder.CreateVectorOfTables(offsets);
  }

  public static Profile? __lookup_by_key(int vectorLocation, string key, ByteBuffer bb) {
    byte[] byteKey = System.Text.Encoding.UTF8.GetBytes(key);
    int span = bb.GetInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = Table.__indirect(vectorLocation + 4 * (start + middle), bb);
      int comp = Table.CompareStrings(Table.__offset(4, bb.Length - tableOffset, bb), byteKey, bb);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return new Profile().__assign(tableOffset, bb);
      }
    }
    return null;
  }
};

public struct SaveRoot : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static SaveRoot GetRootAsSaveRoot(ByteBuffer _bb) { return GetRootAsSaveRoot(_bb, new SaveRoot()); }
  public static SaveRoot GetRootAsSaveRoot(ByteBuffer _bb, SaveRoot obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool SaveRootBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "CSAV"); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SaveRoot __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string SchemaVersion { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSchemaVersionBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetSchemaVersionBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetSchemaVersionArray() { return __p.__vector_as_array<byte>(4); }
  public Claw.Save.Profile? Profiles(int j) { int o = __p.__offset(6); return o != 0 ? (Claw.Save.Profile?)(new Claw.Save.Profile()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ProfilesLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Claw.Save.Profile? ProfilesByKey(string key) { int o = __p.__offset(6); return o != 0 ? Claw.Save.Profile.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }

  public static Offset<Claw.Save.SaveRoot> CreateSaveRoot(FlatBufferBuilder builder,
      StringOffset schema_versionOffset = default(StringOffset),
      VectorOffset profilesOffset = default(VectorOffset)) {
    builder.StartTable(2);
    SaveRoot.AddProfiles(builder, profilesOffset);
    SaveRoot.AddSchemaVersion(builder, schema_versionOffset);
    return SaveRoot.EndSaveRoot(builder);
  }

  public static void StartSaveRoot(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddSchemaVersion(FlatBufferBuilder builder, StringOffset schemaVersionOffset) { builder.AddOffset(0, schemaVersionOffset.Value, 0); }
  public static void AddProfiles(FlatBufferBuilder builder, VectorOffset profilesOffset) { builder.AddOffset(1, profilesOffset.Value, 0); }
  public static VectorOffset CreateProfilesVector(FlatBufferBuilder builder, Offset<Claw.Save.Profile>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateProfilesVectorBlock(FlatBufferBuilder builder, Offset<Claw.Save.Profile>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartProfilesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Claw.Save.SaveRoot> EndSaveRoot(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Claw.Save.SaveRoot>(o);
  }
  public static void FinishSaveRootBuffer(FlatBufferBuilder builder, Offset<Claw.Save.SaveRoot> offset) { builder.Finish(offset.Value, "CSAV"); }
  public static void FinishSizePrefixedSaveRootBuffer(FlatBufferBuilder builder, Offset<Claw.Save.SaveRoot> offset) { builder.FinishSizePrefixed(offset.Value, "CSAV"); }
};


}
