// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Claw.TData
{

using global::System;
using global::FlatBuffers;

public enum Currency : sbyte
{
  Coins = 0,
  Tokens = 1,
};

public enum Quality : sbyte
{
  White = 0,
  Green = 1,
  Blue = 2,
  Purple = 3,
  Red = 4,
  Rainbow = 5,
};

public struct ItemDef : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static ItemDef GetRootAsItemDef(ByteBuffer _bb) { return GetRootAsItemDef(_bb, new ItemDef()); }
  public static ItemDef GetRootAsItemDef(ByteBuffer _bb, ItemDef obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ItemDef __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Id { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetIdArray() { return __p.__vector_as_array<byte>(4); }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
  public Claw.TData.Quality Quality { get { int o = __p.__offset(8); return o != 0 ? (Claw.TData.Quality)__p.bb.GetSbyte(o + __p.bb_pos) : Claw.TData.Quality.White; } }
  public string Description { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescriptionBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetDescriptionBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetDescriptionArray() { return __p.__vector_as_array<byte>(10); }
  public string IconPath { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIconPathBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetIconPathBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetIconPathArray() { return __p.__vector_as_array<byte>(12); }
  public float BaseCatchProbability { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float RefreshWeight { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)1.0f; } }
  public ushort RefreshMin { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public ushort RefreshMax { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }

  public static Offset<Claw.TData.ItemDef> CreateItemDef(FlatBufferBuilder builder,
      StringOffset idOffset = default(StringOffset),
      StringOffset nameOffset = default(StringOffset),
      Claw.TData.Quality quality = Claw.TData.Quality.White,
      StringOffset descriptionOffset = default(StringOffset),
      StringOffset icon_pathOffset = default(StringOffset),
      float base_catch_probability = 0.0f,
      float refresh_weight = 1.0f,
      ushort refresh_min = 0,
      ushort refresh_max = 0) {
    builder.StartTable(9);
    ItemDef.AddRefreshWeight(builder, refresh_weight);
    ItemDef.AddBaseCatchProbability(builder, base_catch_probability);
    ItemDef.AddIconPath(builder, icon_pathOffset);
    ItemDef.AddDescription(builder, descriptionOffset);
    ItemDef.AddName(builder, nameOffset);
    ItemDef.AddId(builder, idOffset);
    ItemDef.AddRefreshMax(builder, refresh_max);
    ItemDef.AddRefreshMin(builder, refresh_min);
    ItemDef.AddQuality(builder, quality);
    return ItemDef.EndItemDef(builder);
  }

  public static void StartItemDef(FlatBufferBuilder builder) { builder.StartTable(9); }
  public static void AddId(FlatBufferBuilder builder, StringOffset idOffset) { builder.AddOffset(0, idOffset.Value, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddQuality(FlatBufferBuilder builder, Claw.TData.Quality quality) { builder.AddSbyte(2, (sbyte)quality, 0); }
  public static void AddDescription(FlatBufferBuilder builder, StringOffset descriptionOffset) { builder.AddOffset(3, descriptionOffset.Value, 0); }
  public static void AddIconPath(FlatBufferBuilder builder, StringOffset iconPathOffset) { builder.AddOffset(4, iconPathOffset.Value, 0); }
  public static void AddBaseCatchProbability(FlatBufferBuilder builder, float baseCatchProbability) { builder.AddFloat(5, baseCatchProbability, 0.0f); }
  public static void AddRefreshWeight(FlatBufferBuilder builder, float refreshWeight) { builder.AddFloat(6, refreshWeight, 1.0f); }
  public static void AddRefreshMin(FlatBufferBuilder builder, ushort refreshMin) { builder.AddUshort(7, refreshMin, 0); }
  public static void AddRefreshMax(FlatBufferBuilder builder, ushort refreshMax) { builder.AddUshort(8, refreshMax, 0); }
  public static Offset<Claw.TData.ItemDef> EndItemDef(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // id
    return new Offset<Claw.TData.ItemDef>(o);
  }

  public static VectorOffset CreateSortedVectorOfItemDef(FlatBufferBuilder builder, Offset<ItemDef>[] offsets) {
    Array.Sort(offsets, (Offset<ItemDef> o1, Offset<ItemDef> o2) => Table.CompareStrings(Table.__offset(4, o1.Value, builder.DataBuffer), Table.__offset(4, o2.Value, builder.DataBuffer), builder.DataBuffer));
    return builder.CreateVectorOfTables(offsets);
  }

  public static ItemDef? __lookup_by_key(int vectorLocation, string key, ByteBuffer bb) {
    byte[] byteKey = System.Text.Encoding.UTF8.GetBytes(key);
    int span = bb.GetInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = Table.__indirect(vectorLocation + 4 * (start + middle), bb);
      int comp = Table.CompareStrings(Table.__offset(4, bb.Length - tableOffset, bb), byteKey, bb);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return new ItemDef().__assign(tableOffset, bb);
      }
    }
    return null;
  }
};

public struct ProbabilityDef : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static ProbabilityDef GetRootAsProbabilityDef(ByteBuffer _bb) { return GetRootAsProbabilityDef(_bb, new ProbabilityDef()); }
  public static ProbabilityDef GetRootAsProbabilityDef(ByteBuffer _bb, ProbabilityDef obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ProbabilityDef __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float DifficultyFactor { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float EnvironmentalCoeffMin { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.7f; } }
  public float EnvironmentalCoeffMax { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)1.1f; } }
  public float DropOnAscentChance { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.1f; } }
  public float SlipOnGrabChance { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.05f; } }

  public static Offset<Claw.TData.ProbabilityDef> CreateProbabilityDef(FlatBufferBuilder builder,
      float difficulty_factor = 0.0f,
      float environmental_coeff_min = 0.7f,
      float environmental_coeff_max = 1.1f,
      float drop_on_ascent_chance = 0.1f,
      float slip_on_grab_chance = 0.05f) {
    builder.StartTable(5);
    ProbabilityDef.AddSlipOnGrabChance(builder, slip_on_grab_chance);
    ProbabilityDef.AddDropOnAscentChance(builder, drop_on_ascent_chance);
    ProbabilityDef.AddEnvironmentalCoeffMax(builder, environmental_coeff_max);
    ProbabilityDef.AddEnvironmentalCoeffMin(builder, environmental_coeff_min);
    ProbabilityDef.AddDifficultyFactor(builder, difficulty_factor);
    return ProbabilityDef.EndProbabilityDef(builder);
  }

  public static void StartProbabilityDef(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddDifficultyFactor(FlatBufferBuilder builder, float difficultyFactor) { builder.AddFloat(0, difficultyFactor, 0.0f); }
  public static void AddEnvironmentalCoeffMin(FlatBufferBuilder builder, float environmentalCoeffMin) { builder.AddFloat(1, environmentalCoeffMin, 0.7f); }
  public static void AddEnvironmentalCoeffMax(FlatBufferBuilder builder, float environmentalCoeffMax) { builder.AddFloat(2, environmentalCoeffMax, 1.1f); }
  public static void AddDropOnAscentChance(FlatBufferBuilder builder, float dropOnAscentChance) { builder.AddFloat(3, dropOnAscentChance, 0.1f); }
  public static void AddSlipOnGrabChance(FlatBufferBuilder builder, float slipOnGrabChance) { builder.AddFloat(4, slipOnGrabChance, 0.05f); }
  public static Offset<Claw.TData.ProbabilityDef> EndProbabilityDef(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Claw.TData.ProbabilityDef>(o);
  }
};

public struct GuaranteeBand : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static GuaranteeBand GetRootAsGuaranteeBand(ByteBuffer _bb) { return GetRootAsGuaranteeBand(_bb, new GuaranteeBand()); }
  public static GuaranteeBand GetRootAsGuaranteeBand(ByteBuffer _bb, GuaranteeBand obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GuaranteeBand __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Claw.TData.Quality Quality { get { int o = __p.__offset(4); return o != 0 ? (Claw.TData.Quality)__p.bb.GetSbyte(o + __p.bb_pos) : Claw.TData.Quality.White; } }
  public ushort FailThreshold { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }

  public static Offset<Claw.TData.GuaranteeBand> CreateGuaranteeBand(FlatBufferBuilder builder,
      Claw.TData.Quality quality = Claw.TData.Quality.White,
      ushort fail_threshold = 0) {
    builder.StartTable(2);
    GuaranteeBand.AddFailThreshold(builder, fail_threshold);
    GuaranteeBand.AddQuality(builder, quality);
    return GuaranteeBand.EndGuaranteeBand(builder);
  }

  public static void StartGuaranteeBand(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddQuality(FlatBufferBuilder builder, Claw.TData.Quality quality) { builder.AddSbyte(0, (sbyte)quality, 0); }
  public static void AddFailThreshold(FlatBufferBuilder builder, ushort failThreshold) { builder.AddUshort(1, failThreshold, 0); }
  public static Offset<Claw.TData.GuaranteeBand> EndGuaranteeBand(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Claw.TData.GuaranteeBand>(o);
  }
};

public struct MachineRules : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static MachineRules GetRootAsMachineRules(ByteBuffer _bb) { return GetRootAsMachineRules(_bb, new MachineRules()); }
  public static MachineRules GetRootAsMachineRules(ByteBuffer _bb, MachineRules obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MachineRules __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Claw.TData.Currency CostCurrency { get { int o = __p.__offset(4); return o != 0 ? (Claw.TData.Currency)__p.bb.GetSbyte(o + __p.bb_pos) : Claw.TData.Currency.Coins; } }
  public ushort CostPerPlay { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)1; } }
  public ushort CountdownSeconds { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)20; } }
  public bool AllowDiagonals { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)true; } }

  public static Offset<Claw.TData.MachineRules> CreateMachineRules(FlatBufferBuilder builder,
      Claw.TData.Currency cost_currency = Claw.TData.Currency.Coins,
      ushort cost_per_play = 1,
      ushort countdown_seconds = 20,
      bool allow_diagonals = true) {
    builder.StartTable(4);
    MachineRules.AddCountdownSeconds(builder, countdown_seconds);
    MachineRules.AddCostPerPlay(builder, cost_per_play);
    MachineRules.AddAllowDiagonals(builder, allow_diagonals);
    MachineRules.AddCostCurrency(builder, cost_currency);
    return MachineRules.EndMachineRules(builder);
  }

  public static void StartMachineRules(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddCostCurrency(FlatBufferBuilder builder, Claw.TData.Currency costCurrency) { builder.AddSbyte(0, (sbyte)costCurrency, 0); }
  public static void AddCostPerPlay(FlatBufferBuilder builder, ushort costPerPlay) { builder.AddUshort(1, costPerPlay, 1); }
  public static void AddCountdownSeconds(FlatBufferBuilder builder, ushort countdownSeconds) { builder.AddUshort(2, countdownSeconds, 20); }
  public static void AddAllowDiagonals(FlatBufferBuilder builder, bool allowDiagonals) { builder.AddBool(3, allowDiagonals, true); }
  public static Offset<Claw.TData.MachineRules> EndMachineRules(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Claw.TData.MachineRules>(o);
  }
};

public struct InventoryRule : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static InventoryRule GetRootAsInventoryRule(ByteBuffer _bb) { return GetRootAsInventoryRule(_bb, new InventoryRule()); }
  public static InventoryRule GetRootAsInventoryRule(ByteBuffer _bb, InventoryRule obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public InventoryRule __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort MinTotal { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)20; } }
  public ushort MaxTotal { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)80; } }

  public static Offset<Claw.TData.InventoryRule> CreateInventoryRule(FlatBufferBuilder builder,
      ushort min_total = 20,
      ushort max_total = 80) {
    builder.StartTable(2);
    InventoryRule.AddMaxTotal(builder, max_total);
    InventoryRule.AddMinTotal(builder, min_total);
    return InventoryRule.EndInventoryRule(builder);
  }

  public static void StartInventoryRule(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddMinTotal(FlatBufferBuilder builder, ushort minTotal) { builder.AddUshort(0, minTotal, 20); }
  public static void AddMaxTotal(FlatBufferBuilder builder, ushort maxTotal) { builder.AddUshort(1, maxTotal, 80); }
  public static Offset<Claw.TData.InventoryRule> EndInventoryRule(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Claw.TData.InventoryRule>(o);
  }
};

public struct MachineDef : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static MachineDef GetRootAsMachineDef(ByteBuffer _bb) { return GetRootAsMachineDef(_bb, new MachineDef()); }
  public static MachineDef GetRootAsMachineDef(ByteBuffer _bb, MachineDef obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MachineDef __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Id { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetIdArray() { return __p.__vector_as_array<byte>(4); }
  public Claw.TData.MachineRules? Rules { get { int o = __p.__offset(6); return o != 0 ? (Claw.TData.MachineRules?)(new Claw.TData.MachineRules()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public Claw.TData.InventoryRule? InventoryRule { get { int o = __p.__offset(8); return o != 0 ? (Claw.TData.InventoryRule?)(new Claw.TData.InventoryRule()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public Claw.TData.ProbabilityDef? Probability { get { int o = __p.__offset(10); return o != 0 ? (Claw.TData.ProbabilityDef?)(new Claw.TData.ProbabilityDef()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public Claw.TData.GuaranteeBand? Guarantee(int j) { int o = __p.__offset(12); return o != 0 ? (Claw.TData.GuaranteeBand?)(new Claw.TData.GuaranteeBand()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int GuaranteeLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Claw.TData.ItemDef? Items(int j) { int o = __p.__offset(14); return o != 0 ? (Claw.TData.ItemDef?)(new Claw.TData.ItemDef()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ItemsLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Claw.TData.ItemDef? ItemsByKey(string key) { int o = __p.__offset(14); return o != 0 ? Claw.TData.ItemDef.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }

  public static Offset<Claw.TData.MachineDef> CreateMachineDef(FlatBufferBuilder builder,
      StringOffset idOffset = default(StringOffset),
      Offset<Claw.TData.MachineRules> rulesOffset = default(Offset<Claw.TData.MachineRules>),
      Offset<Claw.TData.InventoryRule> inventory_ruleOffset = default(Offset<Claw.TData.InventoryRule>),
      Offset<Claw.TData.ProbabilityDef> probabilityOffset = default(Offset<Claw.TData.ProbabilityDef>),
      VectorOffset guaranteeOffset = default(VectorOffset),
      VectorOffset itemsOffset = default(VectorOffset)) {
    builder.StartTable(6);
    MachineDef.AddItems(builder, itemsOffset);
    MachineDef.AddGuarantee(builder, guaranteeOffset);
    MachineDef.AddProbability(builder, probabilityOffset);
    MachineDef.AddInventoryRule(builder, inventory_ruleOffset);
    MachineDef.AddRules(builder, rulesOffset);
    MachineDef.AddId(builder, idOffset);
    return MachineDef.EndMachineDef(builder);
  }

  public static void StartMachineDef(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddId(FlatBufferBuilder builder, StringOffset idOffset) { builder.AddOffset(0, idOffset.Value, 0); }
  public static void AddRules(FlatBufferBuilder builder, Offset<Claw.TData.MachineRules> rulesOffset) { builder.AddOffset(1, rulesOffset.Value, 0); }
  public static void AddInventoryRule(FlatBufferBuilder builder, Offset<Claw.TData.InventoryRule> inventoryRuleOffset) { builder.AddOffset(2, inventoryRuleOffset.Value, 0); }
  public static void AddProbability(FlatBufferBuilder builder, Offset<Claw.TData.ProbabilityDef> probabilityOffset) { builder.AddOffset(3, probabilityOffset.Value, 0); }
  public static void AddGuarantee(FlatBufferBuilder builder, VectorOffset guaranteeOffset) { builder.AddOffset(4, guaranteeOffset.Value, 0); }
  public static VectorOffset CreateGuaranteeVector(FlatBufferBuilder builder, Offset<Claw.TData.GuaranteeBand>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateGuaranteeVectorBlock(FlatBufferBuilder builder, Offset<Claw.TData.GuaranteeBand>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartGuaranteeVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddItems(FlatBufferBuilder builder, VectorOffset itemsOffset) { builder.AddOffset(5, itemsOffset.Value, 0); }
  public static VectorOffset CreateItemsVector(FlatBufferBuilder builder, Offset<Claw.TData.ItemDef>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, Offset<Claw.TData.ItemDef>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartItemsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Claw.TData.MachineDef> EndMachineDef(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // id
    return new Offset<Claw.TData.MachineDef>(o);
  }

  public static VectorOffset CreateSortedVectorOfMachineDef(FlatBufferBuilder builder, Offset<MachineDef>[] offsets) {
    Array.Sort(offsets, (Offset<MachineDef> o1, Offset<MachineDef> o2) => Table.CompareStrings(Table.__offset(4, o1.Value, builder.DataBuffer), Table.__offset(4, o2.Value, builder.DataBuffer), builder.DataBuffer));
    return builder.CreateVectorOfTables(offsets);
  }

  public static MachineDef? __lookup_by_key(int vectorLocation, string key, ByteBuffer bb) {
    byte[] byteKey = System.Text.Encoding.UTF8.GetBytes(key);
    int span = bb.GetInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = Table.__indirect(vectorLocation + 4 * (start + middle), bb);
      int comp = Table.CompareStrings(Table.__offset(4, bb.Length - tableOffset, bb), byteKey, bb);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return new MachineDef().__assign(tableOffset, bb);
      }
    }
    return null;
  }
};

public struct AudioVisualDef : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static AudioVisualDef GetRootAsAudioVisualDef(ByteBuffer _bb) { return GetRootAsAudioVisualDef(_bb, new AudioVisualDef()); }
  public static AudioVisualDef GetRootAsAudioVisualDef(ByteBuffer _bb, AudioVisualDef obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AudioVisualDef __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string BgmLoop { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetBgmLoopBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetBgmLoopBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetBgmLoopArray() { return __p.__vector_as_array<byte>(4); }
  public string SfxClawMove { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSfxClawMoveBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetSfxClawMoveBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetSfxClawMoveArray() { return __p.__vector_as_array<byte>(6); }
  public string SfxClawClick { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSfxClawClickBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetSfxClawClickBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetSfxClawClickArray() { return __p.__vector_as_array<byte>(8); }
  public string SfxSuccess { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSfxSuccessBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetSfxSuccessBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetSfxSuccessArray() { return __p.__vector_as_array<byte>(10); }
  public string SfxCollision { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSfxCollisionBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetSfxCollisionBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetSfxCollisionArray() { return __p.__vector_as_array<byte>(12); }
  public string CongratsPopupAnim { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCongratsPopupAnimBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetCongratsPopupAnimBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetCongratsPopupAnimArray() { return __p.__vector_as_array<byte>(14); }

  public static Offset<Claw.TData.AudioVisualDef> CreateAudioVisualDef(FlatBufferBuilder builder,
      StringOffset bgm_loopOffset = default(StringOffset),
      StringOffset sfx_claw_moveOffset = default(StringOffset),
      StringOffset sfx_claw_clickOffset = default(StringOffset),
      StringOffset sfx_successOffset = default(StringOffset),
      StringOffset sfx_collisionOffset = default(StringOffset),
      StringOffset congrats_popup_animOffset = default(StringOffset)) {
    builder.StartTable(6);
    AudioVisualDef.AddCongratsPopupAnim(builder, congrats_popup_animOffset);
    AudioVisualDef.AddSfxCollision(builder, sfx_collisionOffset);
    AudioVisualDef.AddSfxSuccess(builder, sfx_successOffset);
    AudioVisualDef.AddSfxClawClick(builder, sfx_claw_clickOffset);
    AudioVisualDef.AddSfxClawMove(builder, sfx_claw_moveOffset);
    AudioVisualDef.AddBgmLoop(builder, bgm_loopOffset);
    return AudioVisualDef.EndAudioVisualDef(builder);
  }

  public static void StartAudioVisualDef(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddBgmLoop(FlatBufferBuilder builder, StringOffset bgmLoopOffset) { builder.AddOffset(0, bgmLoopOffset.Value, 0); }
  public static void AddSfxClawMove(FlatBufferBuilder builder, StringOffset sfxClawMoveOffset) { builder.AddOffset(1, sfxClawMoveOffset.Value, 0); }
  public static void AddSfxClawClick(FlatBufferBuilder builder, StringOffset sfxClawClickOffset) { builder.AddOffset(2, sfxClawClickOffset.Value, 0); }
  public static void AddSfxSuccess(FlatBufferBuilder builder, StringOffset sfxSuccessOffset) { builder.AddOffset(3, sfxSuccessOffset.Value, 0); }
  public static void AddSfxCollision(FlatBufferBuilder builder, StringOffset sfxCollisionOffset) { builder.AddOffset(4, sfxCollisionOffset.Value, 0); }
  public static void AddCongratsPopupAnim(FlatBufferBuilder builder, StringOffset congratsPopupAnimOffset) { builder.AddOffset(5, congratsPopupAnimOffset.Value, 0); }
  public static Offset<Claw.TData.AudioVisualDef> EndAudioVisualDef(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Claw.TData.AudioVisualDef>(o);
  }
};

public struct GameDB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static GameDB GetRootAsGameDB(ByteBuffer _bb) { return GetRootAsGameDB(_bb, new GameDB()); }
  public static GameDB GetRootAsGameDB(ByteBuffer _bb, GameDB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool GameDBBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "CTDB"); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GameDB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Version { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVersionBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetVersionBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetVersionArray() { return __p.__vector_as_array<byte>(4); }
  public Claw.TData.MachineDef? Machines(int j) { int o = __p.__offset(6); return o != 0 ? (Claw.TData.MachineDef?)(new Claw.TData.MachineDef()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int MachinesLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Claw.TData.MachineDef? MachinesByKey(string key) { int o = __p.__offset(6); return o != 0 ? Claw.TData.MachineDef.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }
  public Claw.TData.AudioVisualDef? Av { get { int o = __p.__offset(8); return o != 0 ? (Claw.TData.AudioVisualDef?)(new Claw.TData.AudioVisualDef()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Claw.TData.GameDB> CreateGameDB(FlatBufferBuilder builder,
      StringOffset versionOffset = default(StringOffset),
      VectorOffset machinesOffset = default(VectorOffset),
      Offset<Claw.TData.AudioVisualDef> avOffset = default(Offset<Claw.TData.AudioVisualDef>)) {
    builder.StartTable(3);
    GameDB.AddAv(builder, avOffset);
    GameDB.AddMachines(builder, machinesOffset);
    GameDB.AddVersion(builder, versionOffset);
    return GameDB.EndGameDB(builder);
  }

  public static void StartGameDB(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddVersion(FlatBufferBuilder builder, StringOffset versionOffset) { builder.AddOffset(0, versionOffset.Value, 0); }
  public static void AddMachines(FlatBufferBuilder builder, VectorOffset machinesOffset) { builder.AddOffset(1, machinesOffset.Value, 0); }
  public static VectorOffset CreateMachinesVector(FlatBufferBuilder builder, Offset<Claw.TData.MachineDef>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMachinesVectorBlock(FlatBufferBuilder builder, Offset<Claw.TData.MachineDef>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartMachinesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddAv(FlatBufferBuilder builder, Offset<Claw.TData.AudioVisualDef> avOffset) { builder.AddOffset(2, avOffset.Value, 0); }
  public static Offset<Claw.TData.GameDB> EndGameDB(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Claw.TData.GameDB>(o);
  }
  public static void FinishGameDBBuffer(FlatBufferBuilder builder, Offset<Claw.TData.GameDB> offset) { builder.Finish(offset.Value, "CTDB"); }
  public static void FinishSizePrefixedGameDBBuffer(FlatBufferBuilder builder, Offset<Claw.TData.GameDB> offset) { builder.FinishSizePrefixed(offset.Value, "CTDB"); }
};


}
