// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Claw.Sample
{

using global::System;
using global::FlatBuffers;

public struct Vec3 : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static Vec3 GetRootAsVec3(ByteBuffer _bb) { return GetRootAsVec3(_bb, new Vec3()); }
  public static Vec3 GetRootAsVec3(ByteBuffer _bb, Vec3 obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Vec3 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float X { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Y { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Z { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<Claw.Sample.Vec3> CreateVec3(FlatBufferBuilder builder,
      float x = 0.0f,
      float y = 0.0f,
      float z = 0.0f) {
    builder.StartTable(3);
    Vec3.AddZ(builder, z);
    Vec3.AddY(builder, y);
    Vec3.AddX(builder, x);
    return Vec3.EndVec3(builder);
  }

  public static void StartVec3(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddX(FlatBufferBuilder builder, float x) { builder.AddFloat(0, x, 0.0f); }
  public static void AddY(FlatBufferBuilder builder, float y) { builder.AddFloat(1, y, 0.0f); }
  public static void AddZ(FlatBufferBuilder builder, float z) { builder.AddFloat(2, z, 0.0f); }
  public static Offset<Claw.Sample.Vec3> EndVec3(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Claw.Sample.Vec3>(o);
  }
};

public struct ObjectPositions : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static ObjectPositions GetRootAsObjectPositions(ByteBuffer _bb) { return GetRootAsObjectPositions(_bb, new ObjectPositions()); }
  public static ObjectPositions GetRootAsObjectPositions(ByteBuffer _bb, ObjectPositions obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ObjectPositions __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Claw.Sample.Vec3? ObjectList(int j) { int o = __p.__offset(4); return o != 0 ? (Claw.Sample.Vec3?)(new Claw.Sample.Vec3()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ObjectListLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Claw.Sample.ObjectPositions> CreateObjectPositions(FlatBufferBuilder builder,
      VectorOffset ObjectListOffset = default(VectorOffset)) {
    builder.StartTable(1);
    ObjectPositions.AddObjectList(builder, ObjectListOffset);
    return ObjectPositions.EndObjectPositions(builder);
  }

  public static void StartObjectPositions(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddObjectList(FlatBufferBuilder builder, VectorOffset ObjectListOffset) { builder.AddOffset(0, ObjectListOffset.Value, 0); }
  public static VectorOffset CreateObjectListVector(FlatBufferBuilder builder, Offset<Claw.Sample.Vec3>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateObjectListVectorBlock(FlatBufferBuilder builder, Offset<Claw.Sample.Vec3>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartObjectListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Claw.Sample.ObjectPositions> EndObjectPositions(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Claw.Sample.ObjectPositions>(o);
  }
  public static void FinishObjectPositionsBuffer(FlatBufferBuilder builder, Offset<Claw.Sample.ObjectPositions> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedObjectPositionsBuffer(FlatBufferBuilder builder, Offset<Claw.Sample.ObjectPositions> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
